package client;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keval Sanghvi
 */
public class UsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    
    // Default Fields and References
    String user;
    HashMap<String, Integer> allUsers;
    ChatFrame chatFrame;
    public UsersPanel(String user, HashMap<String, Integer> allUsers, ChatFrame chatFrame) {
        initComponents();
        this.user = user;
        setUsername(user);
        this.allUsers = allUsers;
        this.chatFrame = chatFrame;
        modifyUsersPanel();
    }
    
    // This method sets a label welcoming user.
    private void setUsername(String user) {
        username.setText("Welcome, " + user);
    }
    
    // This method adds users to UsersPanel.
    private void modifyUsersPanel() {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(new Color(18, 140, 126));
        JScrollPane usersPanel = new JScrollPane(panel);
        usersPanel.setBorder(BorderFactory.createLineBorder(new Color(5, 69, 61)));
        usersPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);  
        usersPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);  
        usersPanel.setBounds(0, 75, 350, 625);
        TreeMap<String, Integer> sortedUsers = new TreeMap<>(allUsers);
        for(Map.Entry<String, Integer> sortedUser : sortedUsers.entrySet()) {
            if(!sortedUser.getKey().equals(user)) {
                panel.add(new UserPanel(sortedUser.getKey(), sortedUser.getValue(), chatFrame));
            }
        }
        add(usersPanel);
        panel.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSection = new javax.swing.JPanel();
        username = new javax.swing.JLabel();

        userSection.setBackground(new java.awt.Color(5, 69, 61));

        username.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout userSectionLayout = new javax.swing.GroupLayout(userSection);
        userSection.setLayout(userSectionLayout);
        userSectionLayout.setHorizontalGroup(
            userSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSectionLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        userSectionLayout.setVerticalGroup(
            userSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSectionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 625, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel userSection;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}