package client;

import core.JSONRead;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keval Sanghvi
 */
public class UserPanel extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form UserPanel
     */
    
    // Default Fields and References
    String username;
    int online;
    ChatFrame chatFrame;
    public UserPanel(String username, int online, ChatFrame chatFrame) {
        initComponents();
        this.username = username;
        this.online = online;
        this.chatFrame = chatFrame;
        setMaximumSize(new Dimension(350, 65));
        setSize(new Dimension(350, 65));
        setPreferredSize(new Dimension(350, 65));
        if(online == 1) {
            onlineStatus.setBackground(new Color(37, 211, 102));
        }
        user.setText(username);
        addMouseListener(this);
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("src\\client\\images\\icon.png").getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        labelImage.setIcon(imageIcon);
    }
    
    @Override
    public void mouseClicked(MouseEvent me) {
        Object src = me.getSource();
        if(src instanceof UserPanel) {
            UserPanel user = (UserPanel)src;
            chatFrame.updateChatPanel(username, online);
            JSONRead jsonRead = new JSONRead(chatFrame.getUsername(), username, "client");
            chatFrame.updateMessagePanel(jsonRead.getMessageList());
        }
    }

    @Override
    public void mouseEntered(MouseEvent me) {
        Object src = me.getSource();
        if(src instanceof UserPanel) {
            UserPanel user = (UserPanel)src;
            user.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }

    @Override
    public void mouseReleased(MouseEvent me) {}

    @Override
    public void mousePressed(MouseEvent me) {}

    @Override
    public void mouseExited(MouseEvent me) {
        Object src = me.getSource();
        if(src instanceof UserPanel) {
            UserPanel user = (UserPanel)src;
            user.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        onlineStatus = new javax.swing.JPanel();
        labelImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(7, 94, 84));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(5, 59, 61)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));

        onlineStatus.setBackground(new java.awt.Color(7, 94, 84));
        onlineStatus.setPreferredSize(new java.awt.Dimension(12, 12));

        javax.swing.GroupLayout onlineStatusLayout = new javax.swing.GroupLayout(onlineStatus);
        onlineStatus.setLayout(onlineStatusLayout);
        onlineStatusLayout.setHorizontalGroup(
            onlineStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        onlineStatusLayout.setVerticalGroup(
            onlineStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        labelImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelImage)
                .addGap(44, 44, 44)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(onlineStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onlineStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelImage)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(user)
                            .addGap(40, 40, 40)))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelImage;
    private javax.swing.JPanel onlineStatus;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
